### ISSUE TITLE
Just notice: Starting to integrate

### ISSUE THREAD

**Issue by fetus-hina** [hacceuee/s3-pixel-icons#2]
Please close this issue when you have read it.

----

I have begun integrating this work into stat.ink.
Now, it is used for some of the links on the top page and some of the statistics pages.
It is already deployed and you can see it on your screen.

I think, in the future, this project would be good to release as a individual [NPM](https://www.npmjs.com/) package, but at this time I have [copied the images and LICENSE file](https://github.com/fetus-hina/stat.ink/tree/8996c39bac7accdf754f59b7d9d84b272be1c85d/resources/s3-pixel-icons) to my project.

**Comment by hacceuee** [comment]
@fetus-hina I think I have released the files as an NPM package here: https://www.npmjs.com/package/@hacceuee/s3-pixel-icons?activeTab=code, but, to be completely honest, I have no idea what I'm doing, so if there are any issues, please feel free to point them out to me! I will continue to publish to that package as I complete more icons.

**Comment by fetus-hina** [comment]
Great!

Mostly trivial stuff, but I've created a few change requests for you. Check them out.
If you have any questions about the changes, please feel free to ask.

**Comment by hacceuee** [comment]
You are awesome! Thank you for adjusting those for me. They have all been merged.
