### ISSUE TITLE
Icon Request: Crowns

### ISSUE THREAD

**Issue by fetus-hina** [hacceuee/s3-pixel-icons#22]
There are probably 3 crowns in Splatoon 3, and stat.ink has 1 implemented and [2 awaiting implementation](https://github.com/fetus-hina/stat.ink/issues/1227).

- X Battle: Top 500 players (implemented)
- Splatfest: 100x winner (awaiting)
- Splatfest: 333x winner (awaiting)

Official images:
X Battle:
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/81f48720-2582-446c-8b62-458b42e778f4)

Splatfest 100x (L) and 333x (R)
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/96a128eb-c77b-4075-81ea-a9b2a725233e)

I think it would be better to omit those decorations and figure the crown and fish parts.

**Comment by hacceuee** [comment]
@fetus-hina, 
![Top 500 X-Ranked](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/62b1dde4-d3c5-4774-859d-6ab53d0795f6)
![100x Battle](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/cdf990d1-8c89-4309-8f68-17e07215a0de)
![333x Battle](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/24ce2d92-0357-4133-a7aa-335de323bddd)

Do you want them like this, or would you still like the banner embellishment? Both are easy.

**Comment by fetus-hina** [comment]
They are great! 👍 
I will do my best to make the most of each design.

**Comment by hacceuee** [comment]
Feel free to let me know if you have anything different in mind. I'm happy to make any tweaks you need, or try again!
