### ISSUE TITLE
Icons Request: Water Level

### ISSUE THREAD

**Issue by fetus-hina** [hacceuee/s3-pixel-icons#28]
These icons would make it look a little better.

- Low Tide
- Mid Tide (Normal Tide)
- High Tide

Those icons probably do not exist in official resources.

The intent is to display this information in Overfishing Stats and Salmon Run wave details.
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/7d192e24-17ad-452b-af82-229ae7df9f9b)

This is just a rough sketch.
I don't expect a similar design necessarily. If there is a better way to express it, that would be great.
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/dc65a9dc-fbee-4bcf-8af2-3b14bc3b45e5)

**Comment by fetus-hina** [comment]
Thanks for creating the icons!
Now I have deployed the icons, so you can see how they look on the real screen!

**Comment by hacceuee** [comment]
![image](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/4939fd0d-3f26-4c2c-937b-dd54789994e0)

This new set is a bit longer but works well in the space. Let me know if you want the buildings to be lighter or if you would like any color changes.
