### ISSUE TITLE
Icon Creation: Chill Season 2023

### ISSUE THREAD

**Issue by hacceuee** [hacceuee/s3-pixel-icons#29]
Weapon Kits: 
- [ ] Enperry Splat Dualies 
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.1)
- [ ] Neo Splatana Stamper  
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.0)
- [ ] Undercover Sorella Brella
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.0)
- [ ] Deco Reef-flex
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.0)
- [ ] S-Blast '91
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.0)
- [ ] Painbrush Nouveau
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.0)
- [ ] Foil Squeezer
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.0)
- [ ] Custom Blaster
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.1)
- [ ] Snipewriter 5B Nouveau
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.0) 

New Specials: 
- [x] Splattercolor Screen (69a229d8ccb6c1aea36f7d3bc6b7e3b6da3ced31, v 2.1.1)
  - [x] Placeholder (229e733f50b7f68954a74a7c0a5e69420c592d5a, v 2.0.0)
- [x] Triple Splashdown (69a229d8ccb6c1aea36f7d3bc6b7e3b6da3ced31, v 2.1.1)
  - [x] Placeholder (21d8e5e1eb9e65ba1f0a9ef0572d4342ea45ae70, v 2.0.1)

Salmon Run: 
- [x] Megalodontia (4fc3defcbfa106b6dae35e9e551f52a2818945b9, v 2.0.2)
- [x] Boss Meter: Megalodontia (180002bd7b9c6d8980867d4e6218f730421ea091, v 2.10)
- [x] Boss Meter: Houroboros (180002bd7b9c6d8980867d4e6218f730421ea091, v 2.10)

**Comment by fetus-hina** [comment]
https://twitter.com/SplatoonJP/status/1729424896378425516
Splashdown comes back enhanced. It's English name is not known, but in Japanese it is called ウルトラチャクチ (_lit. "Ultra Landing"_; so English name would be Ultra Splashdown or something).
