### ISSUE TITLE
Icon Creation: Fresh Season 2024

### ISSUE THREAD

**Issue by hacceuee** [hacceuee/s3-pixel-icons#33]
Weapon Kits:
- [x] Recycle Brella 24 Mk 1 (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0)
- [x] .52 Gal Deco (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0) (nailed it)
  - [x] Placeholder (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0)
- [x] Douser Dualies (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0)
- [x] New Squiffer (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0)
- [x] Dread Wringer D (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0)
- [x] Foil Flingza Roller (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0)
- [x] Custom E-liter 4K (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0)
- [x] Custom E-liter 4K Scope (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0)
- [x] Custom Explosher (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (24bcc5cc18c344be84c1d9594804e6a5d78c994a, v 2.3.0)
- [x] Nautilus 79 (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Glooga Dualies Deco (!!!! <3 <3) (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)

Salmon Run:
- [x] Bonerattle Arena (bf42302b496cc6fba3a4e1e41889298bf4251e19, v 2.3.9)

DLC Weapon Skins: 
- [x] Blaster (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Brella (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Brush (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Charger (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Dualie (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Roller (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Shooter (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (f719a3d601f96ccffae0ea272ffac295f4209bdc, v 2.3.5)
- [x] Slosher (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Splatana (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Splatling (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
- [x] Stringer (2cb0d3a5300431212b3871edb6a2e94bfe592f43, v 2.3.6)
  - [x] Placeholder (0cd8699cad4879ea443ecbcd0c69e23197e66acb, v 2.3.3)
 - [x] Octo Shot Replica (5fbca11ce0ec6a1abaaee8c0f0bbccefb674e378, v 2.3.8)

**Comment by fetus-hina** [comment]
Order Shooter Replica (DLC Shooter Replica) is listed as being added in 0cd8699, but it does not include in that commit.

**Comment by hacceuee** [comment]
On it! Looks like I didn't include it in the commit.

**Comment by fetus-hina** [comment]
2cb0d3a5300431212b3871edb6a2e94bfe592f43: According to several sources (a) (b), it appears the Order Brush Replica is correct to be a single word, "Orderbrush", not "Order Brush". 
(a) https://splatoonwiki.org/wiki/Orderbrush_Replica
(b) https://leanny.github.io/splat3/database.html

**Comment by hacceuee** [comment]
Everything should be there in 2.3.9! Enjoy :D
