### ISSUE TITLE
No frame ability chunks did not show in NPM package

### ISSUE THREAD

**Issue by zhxie** [hacceuee/s3-pixel-icons#38]
Thanks for your great work and I am using s3-pixel-icons for weapons, sub weapons, special weapons and abilities placeholders in [conch-bay](https://github.com/zhxie/conch-bay).

But no frame ability chunks have been relocated to archived images and did not show in NPM package.

**Comment by hacceuee** [comment]
I moved them back! I did not realize they were being used. The new version is 2.2.12
