### ISSUE TITLE
Icon Request: Season 8 weapons

### ISSUE THREAD

**Issue by fetus-hina** [hacceuee/s3-pixel-icons#39]
New weapons:
- Bamboozler 14 Mk II
- Custom Douser Dualies FF
- Heavy Edit Splatling Nouveau
- Custom Hydra Splatling
- Mint Decavitator
- Charcoal Decavitator
- Custom Range Blaster
- Recycled Brella 24 Mk II
- Wellstring V
- Custom Wellstring V

New grizzco weapon:
- Grizzco Roller (?)

**Comment by hacceuee** [comment]
Weapon Kits:
- [ ] Bamboozler 14 Mk II 
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Custom Douser Dualies FF
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Heavy Edit Splatling Nouveau
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Custom Hydra Splatling
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Mint Decavitator
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Charcoal Decavitator
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Custom Range Blaster
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Recycled Brella 24 Mk II
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Wellstring V
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Custom Wellstring V
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
- [ ] Grizzco Roller (?)
   - [x] Placeholder (https://github.com/hacceuee/s3-pixel-icons/commit/0114a22c94d659cc47fe65431cae70b7aaf44cc4, v 2.3.13)
