### ISSUE TITLE
Icon Request: Battle Scoreboard Icons

### ISSUE THREAD

**Issue by fetus-hina** [hacceuee/s3-pixel-icons#6]
- Kills
- Deaths
- Tricolor TW: Ultra Signal tryes

What I assumed like this: ![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/ce39ef7b-5fa2-450d-8465-b78f62f2baff)

This request is not immediately needed. I would be happy to prepare it at your pace.

**Comment by hacceuee** [comment]
Completed by latest commit (665eaae2d69ad6905ceac37fb1d63c3fca4586ac) and 98c148c72a977f0206143a2f644c6f661816d910
